const AppActionsConstants = {
  UPDATE_TAG: "UPDATE_TAG",
  LOAD_TAGS: "LOAD_TAGS",
  LOAD_TAGS_SUCCESS: "LOAD_TAGS_SUCCESS",
  LOAD_TAGS_FAILURE: "LOAD_TAGS_FAILURE",
  LOAD_USER: "LOAD_USER",
  UPDATE_USER: "UPDATE_USER",
  AUTH: "AUTHENTICATION_FORM_AUTH",
  LOGOUT: "LOGOUT"
};

export { AppActionsConstants };
