const EmailsActionsConstants = {
  EMAILS_LOAD: "EMAILS_LOAD",
  EMAILS_LOAD_SUCC: "EMAILS_LOAD_SUCC",
  EMAILS_LOAD_FAIL: "EMAILS_LOAD_FAIL",
  REMOVE_EMAIL: "REMOVE_EMAIL",
  REMOVE_EMAIL_SUCC: "REMOVE_EMAIL_SUCC",
  REMOVE_EMAIL_FAIL: "REMOVE_EMAIL_FAIL",
};

export { EmailsActionsConstants };
