const ComposeFormConstants = {
  COMPOSE_FORM_SUBMIT: "COMPOSE_FORM_SUBMIT",
  COMPOSE_FORM_SUBMIT_SUCC: "COMPOSE_FORM_SUBMIT_SUCC",
  COMPOSE_FORM_SUBMIT_FAIL: "COMPOSE_FORM_SUBMIT_FAIL",
};

export { ComposeFormConstants };
